# 应用服务 WEB 访问端口
server :
  port : 7065
# 应用名称
spring :
  application :
      name : wiki
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lole-wiki?serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml